// Classification of all state attributes possible
const state_attrb = {
    "alarm" : {
        type: 'boolean',
        role: 'sensor.alarm',
        read: true,
        write: true,
    },
    "ap" : {
        type: 'mixed',
        role: 'info',
        read: true,
        write: true,
    },
    "api_version" : {
        type: 'number',
        role: 'info.api_version',
        read: true,
        write: false,
    },
    "autoupd" : {
        type: 'bolean',
        role: 'info.status',
        read: true,
        write: true,
    },
    "channel" : {
        type: 'number',
        role: 'info.channel',
        read: true,
        write: false,
    },
    "color" : {
        type: 'number',
        role: 'level.color.rgb',
        read: true,
        write: true,
    },
    "device" : {
        type: 'mixed',
        role: 'info.device',
        read: true,
        write: false,
    },
    "god"  : {
        type: 'number',
        role: 'info',
        read: true,
        write: false,
    },
    "host"  : {
        type: 'mixed',
        role: 'info.hostname',
        read: true,
        write: true,
    },
    "hw_version" : {
        type: 'mixed',
        role: 'info.hw_version',
        read: true,
        write: false,
    },
    "hwversion" : {
        type: 'mixed',
        role: 'info.hw_version',
        read: true,
        write: false,
    },
    "item" : {
        type: 'mixed',
        role: 'info.item',
        read: true,
        write: false,
    },
    "id" : {
        type: 'number',
        role: 'info.id',
        read: true,
        write: false,
    },
    "getupdate" : {
        type: 'mixed',
        role: 'info.status',
        read: true,
        write: false,
    },
    "language" : {
        type: 'mixed',
        role: 'info.language',
        read: true,
        write: false,
    },
    "max" : {
        type: 'number',
        role: 'value.max',
        unit: true,
        read: true,
        write: true,
    },
    "min": {
        type: 'number',
        role: 'value.min',
        unit: true,
        read: true,
        write: true,
    },
    "name" : {
        type: 'mixed',
        role: 'info.name',
        read: true,
        write: true,
    },
    "number"  :  {
        type: 'number',
        role: 'value',
        read: true,
        write: false,
    },
    "pid" : {
        type: 'number',
        role: 'info.pid',
        read: true,
        write: true,
    },
    "serial" : {
        type: 'mixed',
        role: 'info.serial',
        read: true,
        write: false,
    },
    "set": {
        type: 'number',
        role: 'value',
        unit: 'unit_device',
        read: true,
        write: true,
    },
    "set_color" : {
        type: 'mixed',
        role: 'level.color.rgb',
        read: true,
        write: true,
    },
    "sw_version" : {
        type: 'mixed',
        role: 'info.sw_version',
        read: true,
        write: false,
    },
    "temp" : {
        type: 'number',
        role: 'value.min',
        unit: true,
        read: true,
        write: false,
    },
    "time" : {
        type: 'mixed',
        role: 'value.time',
        read: true,
        write: false,
    },
    "typ" : {
        type: 'mixed',
        role: 'info.typ',
        read: true,
        write: true,
    },
    "unit" : {
        type: 'mixed',
        role: 'info.unit',
        read: true,
        write: true,
    },
    "value" : {
        type: 'number',
        role: 'value',
        read: true,
        write: true,
    },
    "value_color" : {
        type: 'mixed',
        role: 'level.color.rgb',
        read: true,
        write: false,
    },
    "version" : {
        type: 'mixed',
        role: 'info.version',
        read: true,
        write: false,
    }
}


module.exports = state_attrb;